---
- name: Instalar o nginx
  ansible.builtin.apt:
    name: "nginx={{ nginx_version }}"
    update_cache: yes
    state: present

- name: Configurando o nginx
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Criar diretórios extras vazios
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ nginx_extra_dirs }}"

- name: Criar diretórios para os arquivos extras
  ansible.builtin.file:
    path: "{{ item.destination | dirname }}"
    state: directory
    mode: '0755'
  loop: "{{ nginx_extra_files }}"

- name: Renderizar os arquivos extras
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', item.filename) }}"
    path: "{{ item.destination }}"
    mode: '0644'
    create: true
  loop: "{{ nginx_extra_files }}"

- name: Habilitando nginx
  ansible.builtin.service:
    enabled: yes
    name: nginx
    state: started
