---
- name: Converge
  hosts: all
  tasks:
    - name: "Include iac_role_nginx"
      include_role:
        name: "iac_role_nginx"
      vars:
        nginx_extra_files:
          - destination: /etc/nginx.d/teste1
            filename: ./test-files/teste1.conf
          - destination: /etc/nginx.d/teste2
            filename: ./test-files/teste2.conf
        nginx_extra_dirs:
          - /var/log/teste
